CREATE DATABASE IF NOT EXISTS lash_nouveau_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lash_nouveau_db;


CREATE TABLE IF NOT EXISTS service_types (
    type_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO service_types (name, description) VALUES
('lashes_full_set', 'Full set lash services'),
('refill', 'Refill services'),
('extra', 'Extras and add-ons'),
('brow', 'Brow services');


CREATE TABLE IF NOT EXISTS services (
    service_id INT AUTO_INCREMENT PRIMARY KEY,
    type_id INT NOT NULL,
    label VARCHAR(150) NOT NULL,
    description TEXT NULL,
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    duration_minutes INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (type_id) REFERENCES service_types(type_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO services (type_id, label, description, price, duration_minutes) VALUES
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Classic Full Set', 'Classic lash full set', 120.00, 90),
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Hybrid Full Set', 'Hybrid lash full set', 140.00, 100),
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Volume Full Set', 'Volume lash full set', 160.00, 120),
((SELECT type_id FROM service_types WHERE name='refill'), '2-3 Week Refill', 'Refill for 2-3 weeks', 60.00, 45),
((SELECT type_id FROM service_types WHERE name='refill'), '4-6 Week Refill', 'Refill for 4-6 weeks', 80.00, 60),
((SELECT type_id FROM service_types WHERE name='brow'), 'Brow Shaping', 'Brow shaping and tint', 45.00, 30),
((SELECT type_id FROM service_types WHERE name='extra'), 'Lash Tint', 'Tinting for lashes', 25.00, 20);

INSERT INTO services (type_id, label, price, duration_minutes) VALUES
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Classic', 130, 60),
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Classic Mix', 150, 60),
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Hybrid', 180, 80),
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Volume', 220, 90),
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Wet Set', 200, 80),
((SELECT type_id FROM service_types WHERE name='lashes_full_set'), 'Lash Lift', 100, 45),
((SELECT type_id FROM service_types WHERE name='refill'), 'Classic Refill', 90, 75),
((SELECT type_id FROM service_types WHERE name='refill'), 'Classic Mix Refill', 110, 75),
((SELECT type_id FROM service_types WHERE name='refill'), 'Hybrid Refill', 130, 75),
((SELECT type_id FROM service_types WHERE name='refill'), 'Volume Refill', 160, 75),
((SELECT type_id FROM service_types WHERE name='refill'), 'Wet Set Refill', 150, 75);

INSERT INTO services (type_id, label, price, duration_minutes) VALUES
((SELECT type_id FROM service_types WHERE name='extra'), 'Wispy', 60, 20),
((SELECT type_id FROM service_types WHERE name='extra'), 'Bottom Lashes', 60, 30),
((SELECT type_id FROM service_types WHERE name='extra'), 'Removal', 40, 15);

/* Users table for authentication */
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('user','admin') NOT NULL DEFAULT 'user',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Example: to create an initial admin user, run a small PHP script that uses password_hash() and inserts the row,
-- or manually insert a password hash generated by PHP. Example SQL (replace HASHED_PASSWORD):
-- INSERT INTO users (name, email, password_hash, role) VALUES ('Admin','admin@example.com','HASHED_PASSWORD','admin');


CREATE TABLE IF NOT EXISTS bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_name VARCHAR(100) NOT NULL,
    client_email VARCHAR(150) NULL,
    user_id INT NULL,
    client_phone VARCHAR(20) NOT NULL,
    service_id INT NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    booking_date DATE NOT NULL,
    booking_time TIME NOT NULL,
    duration_minutes INT NOT NULL,
    extras_list TEXT NULL,
    is_home_service BOOLEAN NOT NULL,
    persons TINYINT NOT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (service_id) REFERENCES services(service_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Index for faster lookup of user bookings
CREATE INDEX IF NOT EXISTS idx_bookings_user ON bookings (user_id);

CREATE TABLE IF NOT EXISTS booking_sessions (
    session_id VARCHAR(100) PRIMARY KEY,
    selected_service LONGTEXT NULL,
    selected_extras LONGTEXT NULL,
    additional_persons INT DEFAULT 1,
    home_service TINYINT(1) DEFAULT 0,
    booking_date DATE NULL,
    booking_time TIME NULL,
    booking_notes LONGTEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    INDEX idx_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
